/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace CTFExchange {
      
    export type OrderStruct = {maker: AddressLike, makerAsset: AddressLike, takerAsset: AddressLike, makerAmount: BigNumberish, takerAmount: BigNumberish, salt: BigNumberish, expiry: BigNumberish, side: BigNumberish, signature: BytesLike}

    export type OrderStructOutput = [maker: string, makerAsset: string, takerAsset: string, makerAmount: bigint, takerAmount: bigint, salt: bigint, expiry: bigint, side: bigint, signature: string] & {maker: string, makerAsset: string, takerAsset: string, makerAmount: bigint, takerAmount: bigint, salt: bigint, expiry: bigint, side: bigint, signature: string }
  
    }

  export interface CTFExchangeInterface extends Interface {
    getFunction(nameOrSignature: "DEFAULT_ADMIN_ROLE" | "OPERATOR_ROLE" | "collateral" | "complements" | "conditionIds" | "ctf" | "fillOrder" | "fillOrders" | "filledOrders" | "getCollateral" | "getComplement" | "getConditionId" | "getCtf" | "getOrderStatus" | "getProxyFactory" | "getRoleAdmin" | "getSafeFactory" | "grantRole" | "hasRole" | "hashOrder" | "isOrderFilled" | "matchOrders" | "pauseTrading" | "paused" | "proxyFactory" | "registerToken" | "renounceRole" | "revokeRole" | "setProxyFactory" | "setSafeFactory" | "supportsInterface" | "unpauseTrading"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "OrderFilled" | "OrdersMatched" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked" | "TokenRegistered" | "TradingPaused" | "TradingUnpaused"): EventFragment;

    encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'OPERATOR_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'collateral', values?: undefined): string;
encodeFunctionData(functionFragment: 'complements', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'conditionIds', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'ctf', values?: undefined): string;
encodeFunctionData(functionFragment: 'fillOrder', values: [CTFExchange.OrderStruct, BigNumberish]): string;
encodeFunctionData(functionFragment: 'fillOrders', values: [CTFExchange.OrderStruct[], BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'filledOrders', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getCollateral', values?: undefined): string;
encodeFunctionData(functionFragment: 'getComplement', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getConditionId', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getCtf', values?: undefined): string;
encodeFunctionData(functionFragment: 'getOrderStatus', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getProxyFactory', values?: undefined): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getSafeFactory', values?: undefined): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hashOrder', values: [CTFExchange.OrderStruct]): string;
encodeFunctionData(functionFragment: 'isOrderFilled', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'matchOrders', values: [CTFExchange.OrderStruct, CTFExchange.OrderStruct[], BigNumberish, BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'pauseTrading', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'proxyFactory', values?: undefined): string;
encodeFunctionData(functionFragment: 'registerToken', values: [BigNumberish, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'setProxyFactory', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setSafeFactory', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'unpauseTrading', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'OPERATOR_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'collateral', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'complements', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'conditionIds', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ctf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fillOrder', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fillOrders', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'filledOrders', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCollateral', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getComplement', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getConditionId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCtf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getOrderStatus', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getProxyFactory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSafeFactory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hashOrder', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isOrderFilled', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'matchOrders', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pauseTrading', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proxyFactory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setProxyFactory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setSafeFactory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpauseTrading', data: BytesLike): Result;
  }

  
    export namespace OrderFilledEvent {
      export type InputTuple = [orderHash: BytesLike, maker: AddressLike, taker: AddressLike, makerAssetId: BigNumberish, takerAssetId: BigNumberish, makerAmountFilled: BigNumberish, takerAmountFilled: BigNumberish, fee: BigNumberish];
      export type OutputTuple = [orderHash: string, maker: string, taker: string, makerAssetId: bigint, takerAssetId: bigint, makerAmountFilled: bigint, takerAmountFilled: bigint, fee: bigint];
      export interface OutputObject {orderHash: string, maker: string, taker: string, makerAssetId: bigint, takerAssetId: bigint, makerAmountFilled: bigint, takerAmountFilled: bigint, fee: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OrdersMatchedEvent {
      export type InputTuple = [takerOrderHash: BytesLike, makerOrderHashes: BytesLike[], takerFilled: BigNumberish, makerFilled: BigNumberish[]];
      export type OutputTuple = [takerOrderHash: string, makerOrderHashes: string[], takerFilled: bigint, makerFilled: bigint[]];
      export interface OutputObject {takerOrderHash: string, makerOrderHashes: string[], takerFilled: bigint, makerFilled: bigint[] };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TokenRegisteredEvent {
      export type InputTuple = [token0: BigNumberish, token1: BigNumberish, conditionId: BytesLike];
      export type OutputTuple = [token0: bigint, token1: bigint, conditionId: string];
      export interface OutputObject {token0: bigint, token1: bigint, conditionId: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TradingPausedEvent {
      export type InputTuple = [];
      export type OutputTuple = [];
      export interface OutputObject {};
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TradingUnpausedEvent {
      export type InputTuple = [];
      export type OutputTuple = [];
      export interface OutputObject {};
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface CTFExchange extends BaseContract {
    
    connect(runner?: ContractRunner | null): CTFExchange;
    waitForDeployment(): Promise<this>;

    interface: CTFExchangeInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    OPERATOR_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    collateral: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    complements: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    conditionIds: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    ctf: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    fillOrder: TypedContractMethod<
      [order: CTFExchange.OrderStruct, fillAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    fillOrders: TypedContractMethod<
      [orders: CTFExchange.OrderStruct[], fillAmounts: BigNumberish[], ],
      [void],
      'nonpayable'
    >
    

    
    filledOrders: TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    getCollateral: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getComplement: TypedContractMethod<
      [token: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getConditionId: TypedContractMethod<
      [token: BigNumberish, ],
      [string],
      'view'
    >
    

    
    getCtf: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getOrderStatus: TypedContractMethod<
      [orderHash: BytesLike, ],
      [bigint],
      'view'
    >
    

    
    getProxyFactory: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    getSafeFactory: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    hashOrder: TypedContractMethod<
      [order: CTFExchange.OrderStruct, ],
      [string],
      'view'
    >
    

    
    isOrderFilled: TypedContractMethod<
      [orderHash: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    matchOrders: TypedContractMethod<
      [takerOrder: CTFExchange.OrderStruct, makerOrders: CTFExchange.OrderStruct[], takerFillAmount: BigNumberish, makerFillAmounts: BigNumberish[], ],
      [void],
      'nonpayable'
    >
    

    
    pauseTrading: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    proxyFactory: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    registerToken: TypedContractMethod<
      [token: BigNumberish, complement: BigNumberish, conditionId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setProxyFactory: TypedContractMethod<
      [_newProxyFactory: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setSafeFactory: TypedContractMethod<
      [arg0: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    unpauseTrading: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'OPERATOR_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'collateral'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'complements'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'conditionIds'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'ctf'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'fillOrder'): TypedContractMethod<
      [order: CTFExchange.OrderStruct, fillAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'fillOrders'): TypedContractMethod<
      [orders: CTFExchange.OrderStruct[], fillAmounts: BigNumberish[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'filledOrders'): TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'getCollateral'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getComplement'): TypedContractMethod<
      [token: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getConditionId'): TypedContractMethod<
      [token: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getCtf'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getOrderStatus'): TypedContractMethod<
      [orderHash: BytesLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getProxyFactory'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getSafeFactory'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'hashOrder'): TypedContractMethod<
      [order: CTFExchange.OrderStruct, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'isOrderFilled'): TypedContractMethod<
      [orderHash: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'matchOrders'): TypedContractMethod<
      [takerOrder: CTFExchange.OrderStruct, makerOrders: CTFExchange.OrderStruct[], takerFillAmount: BigNumberish, makerFillAmounts: BigNumberish[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'pauseTrading'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'proxyFactory'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'registerToken'): TypedContractMethod<
      [token: BigNumberish, complement: BigNumberish, conditionId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setProxyFactory'): TypedContractMethod<
      [_newProxyFactory: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setSafeFactory'): TypedContractMethod<
      [arg0: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'unpauseTrading'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'OrderFilled'): TypedContractEvent<OrderFilledEvent.InputTuple, OrderFilledEvent.OutputTuple, OrderFilledEvent.OutputObject>;
getEvent(key: 'OrdersMatched'): TypedContractEvent<OrdersMatchedEvent.InputTuple, OrdersMatchedEvent.OutputTuple, OrdersMatchedEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
getEvent(key: 'TokenRegistered'): TypedContractEvent<TokenRegisteredEvent.InputTuple, TokenRegisteredEvent.OutputTuple, TokenRegisteredEvent.OutputObject>;
getEvent(key: 'TradingPaused'): TypedContractEvent<TradingPausedEvent.InputTuple, TradingPausedEvent.OutputTuple, TradingPausedEvent.OutputObject>;
getEvent(key: 'TradingUnpaused'): TypedContractEvent<TradingUnpausedEvent.InputTuple, TradingUnpausedEvent.OutputTuple, TradingUnpausedEvent.OutputObject>;

    filters: {
      
      'OrderFilled(bytes32,address,address,uint256,uint256,uint256,uint256,uint256)': TypedContractEvent<OrderFilledEvent.InputTuple, OrderFilledEvent.OutputTuple, OrderFilledEvent.OutputObject>;
      OrderFilled: TypedContractEvent<OrderFilledEvent.InputTuple, OrderFilledEvent.OutputTuple, OrderFilledEvent.OutputObject>;
    

      'OrdersMatched(bytes32,bytes32[],uint256,uint256[])': TypedContractEvent<OrdersMatchedEvent.InputTuple, OrdersMatchedEvent.OutputTuple, OrdersMatchedEvent.OutputObject>;
      OrdersMatched: TypedContractEvent<OrdersMatchedEvent.InputTuple, OrdersMatchedEvent.OutputTuple, OrdersMatchedEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    

      'TokenRegistered(uint256,uint256,bytes32)': TypedContractEvent<TokenRegisteredEvent.InputTuple, TokenRegisteredEvent.OutputTuple, TokenRegisteredEvent.OutputObject>;
      TokenRegistered: TypedContractEvent<TokenRegisteredEvent.InputTuple, TokenRegisteredEvent.OutputTuple, TokenRegisteredEvent.OutputObject>;
    

      'TradingPaused()': TypedContractEvent<TradingPausedEvent.InputTuple, TradingPausedEvent.OutputTuple, TradingPausedEvent.OutputObject>;
      TradingPaused: TypedContractEvent<TradingPausedEvent.InputTuple, TradingPausedEvent.OutputTuple, TradingPausedEvent.OutputObject>;
    

      'TradingUnpaused()': TypedContractEvent<TradingUnpausedEvent.InputTuple, TradingUnpausedEvent.OutputTuple, TradingUnpausedEvent.OutputObject>;
      TradingUnpaused: TypedContractEvent<TradingUnpausedEvent.InputTuple, TradingUnpausedEvent.OutputTuple, TradingUnpausedEvent.OutputObject>;
    
    };
  }