/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface MockUSDTFaucetInterface extends Interface {
    getFunction(nameOrSignature: "canRequest" | "emergencyWithdraw" | "faucetActive" | "getFaucetBalance" | "getRemainingAllowance" | "getTimeUntilNextRequest" | "lastWithdrawalTime" | "lockTime" | "maxTotalWithdrawal" | "mockUSDT" | "owner" | "renounceOwnership" | "requestTokens" | "setLockTime" | "setMaxTotalWithdrawal" | "setWithdrawalAmount" | "toggleFaucet" | "totalWithdrawn" | "transferOwnership" | "withdrawalAmount"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "FaucetRefilled" | "FaucetToggled" | "LockTimeUpdated" | "OwnershipTransferred" | "TokensRequested" | "WithdrawalAmountUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'canRequest', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'emergencyWithdraw', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'faucetActive', values?: undefined): string;
encodeFunctionData(functionFragment: 'getFaucetBalance', values?: undefined): string;
encodeFunctionData(functionFragment: 'getRemainingAllowance', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getTimeUntilNextRequest', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'lastWithdrawalTime', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'lockTime', values?: undefined): string;
encodeFunctionData(functionFragment: 'maxTotalWithdrawal', values?: undefined): string;
encodeFunctionData(functionFragment: 'mockUSDT', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'requestTokens', values?: undefined): string;
encodeFunctionData(functionFragment: 'setLockTime', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setMaxTotalWithdrawal', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setWithdrawalAmount', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'toggleFaucet', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalWithdrawn', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'withdrawalAmount', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'canRequest', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'emergencyWithdraw', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'faucetActive', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getFaucetBalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRemainingAllowance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTimeUntilNextRequest', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lastWithdrawalTime', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lockTime', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'maxTotalWithdrawal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mockUSDT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'requestTokens', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setLockTime', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMaxTotalWithdrawal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setWithdrawalAmount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'toggleFaucet', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalWithdrawn', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawalAmount', data: BytesLike): Result;
  }

  
    export namespace FaucetRefilledEvent {
      export type InputTuple = [donor: AddressLike, amount: BigNumberish];
      export type OutputTuple = [donor: string, amount: bigint];
      export interface OutputObject {donor: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FaucetToggledEvent {
      export type InputTuple = [active: boolean];
      export type OutputTuple = [active: boolean];
      export interface OutputObject {active: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LockTimeUpdatedEvent {
      export type InputTuple = [newLockTime: BigNumberish];
      export type OutputTuple = [newLockTime: bigint];
      export interface OutputObject {newLockTime: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TokensRequestedEvent {
      export type InputTuple = [requester: AddressLike, amount: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [requester: string, amount: bigint, timestamp: bigint];
      export interface OutputObject {requester: string, amount: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawalAmountUpdatedEvent {
      export type InputTuple = [newAmount: BigNumberish];
      export type OutputTuple = [newAmount: bigint];
      export interface OutputObject {newAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface MockUSDTFaucet extends BaseContract {
    
    connect(runner?: ContractRunner | null): MockUSDTFaucet;
    waitForDeployment(): Promise<this>;

    interface: MockUSDTFaucetInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    canRequest: TypedContractMethod<
      [user: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    emergencyWithdraw: TypedContractMethod<
      [_amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    faucetActive: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    getFaucetBalance: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getRemainingAllowance: TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getTimeUntilNextRequest: TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    lastWithdrawalTime: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    lockTime: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    maxTotalWithdrawal: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    mockUSDT: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    requestTokens: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setLockTime: TypedContractMethod<
      [_lockTime: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setMaxTotalWithdrawal: TypedContractMethod<
      [_maxAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setWithdrawalAmount: TypedContractMethod<
      [_amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    toggleFaucet: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    totalWithdrawn: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    withdrawalAmount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'canRequest'): TypedContractMethod<
      [user: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'emergencyWithdraw'): TypedContractMethod<
      [_amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'faucetActive'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'getFaucetBalance'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getRemainingAllowance'): TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getTimeUntilNextRequest'): TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'lastWithdrawalTime'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'lockTime'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'maxTotalWithdrawal'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'mockUSDT'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'requestTokens'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setLockTime'): TypedContractMethod<
      [_lockTime: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setMaxTotalWithdrawal'): TypedContractMethod<
      [_maxAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setWithdrawalAmount'): TypedContractMethod<
      [_amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'toggleFaucet'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'totalWithdrawn'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawalAmount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    getEvent(key: 'FaucetRefilled'): TypedContractEvent<FaucetRefilledEvent.InputTuple, FaucetRefilledEvent.OutputTuple, FaucetRefilledEvent.OutputObject>;
getEvent(key: 'FaucetToggled'): TypedContractEvent<FaucetToggledEvent.InputTuple, FaucetToggledEvent.OutputTuple, FaucetToggledEvent.OutputObject>;
getEvent(key: 'LockTimeUpdated'): TypedContractEvent<LockTimeUpdatedEvent.InputTuple, LockTimeUpdatedEvent.OutputTuple, LockTimeUpdatedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'TokensRequested'): TypedContractEvent<TokensRequestedEvent.InputTuple, TokensRequestedEvent.OutputTuple, TokensRequestedEvent.OutputObject>;
getEvent(key: 'WithdrawalAmountUpdated'): TypedContractEvent<WithdrawalAmountUpdatedEvent.InputTuple, WithdrawalAmountUpdatedEvent.OutputTuple, WithdrawalAmountUpdatedEvent.OutputObject>;

    filters: {
      
      'FaucetRefilled(address,uint256)': TypedContractEvent<FaucetRefilledEvent.InputTuple, FaucetRefilledEvent.OutputTuple, FaucetRefilledEvent.OutputObject>;
      FaucetRefilled: TypedContractEvent<FaucetRefilledEvent.InputTuple, FaucetRefilledEvent.OutputTuple, FaucetRefilledEvent.OutputObject>;
    

      'FaucetToggled(bool)': TypedContractEvent<FaucetToggledEvent.InputTuple, FaucetToggledEvent.OutputTuple, FaucetToggledEvent.OutputObject>;
      FaucetToggled: TypedContractEvent<FaucetToggledEvent.InputTuple, FaucetToggledEvent.OutputTuple, FaucetToggledEvent.OutputObject>;
    

      'LockTimeUpdated(uint256)': TypedContractEvent<LockTimeUpdatedEvent.InputTuple, LockTimeUpdatedEvent.OutputTuple, LockTimeUpdatedEvent.OutputObject>;
      LockTimeUpdated: TypedContractEvent<LockTimeUpdatedEvent.InputTuple, LockTimeUpdatedEvent.OutputTuple, LockTimeUpdatedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'TokensRequested(address,uint256,uint256)': TypedContractEvent<TokensRequestedEvent.InputTuple, TokensRequestedEvent.OutputTuple, TokensRequestedEvent.OutputObject>;
      TokensRequested: TypedContractEvent<TokensRequestedEvent.InputTuple, TokensRequestedEvent.OutputTuple, TokensRequestedEvent.OutputObject>;
    

      'WithdrawalAmountUpdated(uint256)': TypedContractEvent<WithdrawalAmountUpdatedEvent.InputTuple, WithdrawalAmountUpdatedEvent.OutputTuple, WithdrawalAmountUpdatedEvent.OutputObject>;
      WithdrawalAmountUpdated: TypedContractEvent<WithdrawalAmountUpdatedEvent.InputTuple, WithdrawalAmountUpdatedEvent.OutputTuple, WithdrawalAmountUpdatedEvent.OutputObject>;
    
    };
  }