/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace ProxyWalletFactory {
      
    export type CallStruct = {to: AddressLike, data: BytesLike, value: BigNumberish}

    export type CallStructOutput = [to: string, data: string, value: bigint] & {to: string, data: string, value: bigint }
  
    }

  export interface ProxyWalletFactoryInterface extends Interface {
    getFunction(nameOrSignature: "getImplementation" | "getInstanceAddress" | "implementation" | "maybeMakeWallet" | "owner" | "proxy" | "renounceOwnership" | "setImplementation" | "transferOwnership"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ImplementationUpdated" | "OwnershipTransferred" | "ProxyCreation"): EventFragment;

    encodeFunctionData(functionFragment: 'getImplementation', values?: undefined): string;
encodeFunctionData(functionFragment: 'getInstanceAddress', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'implementation', values?: undefined): string;
encodeFunctionData(functionFragment: 'maybeMakeWallet', values: [AddressLike, AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'proxy', values: [ProxyWalletFactory.CallStruct[]]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'setImplementation', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'getImplementation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getInstanceAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'implementation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'maybeMakeWallet', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proxy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setImplementation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  }

  
    export namespace ImplementationUpdatedEvent {
      export type InputTuple = [newImplementation: AddressLike];
      export type OutputTuple = [newImplementation: string];
      export interface OutputObject {newImplementation: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProxyCreationEvent {
      export type InputTuple = [instance: AddressLike, user: AddressLike];
      export type OutputTuple = [instance: string, user: string];
      export interface OutputObject {instance: string, user: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ProxyWalletFactory extends BaseContract {
    
    connect(runner?: ContractRunner | null): ProxyWalletFactory;
    waitForDeployment(): Promise<this>;

    interface: ProxyWalletFactoryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getImplementation: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getInstanceAddress: TypedContractMethod<
      [arg0: AddressLike, user: AddressLike, ],
      [string],
      'view'
    >
    

    
    implementation: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    maybeMakeWallet: TypedContractMethod<
      [arg0: AddressLike, instanceAddress: AddressLike, user: AddressLike, ],
      [string],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    proxy: TypedContractMethod<
      [calls: ProxyWalletFactory.CallStruct[], ],
      [string[]],
      'payable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setImplementation: TypedContractMethod<
      [_newImplementation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getImplementation'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getInstanceAddress'): TypedContractMethod<
      [arg0: AddressLike, user: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'implementation'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'maybeMakeWallet'): TypedContractMethod<
      [arg0: AddressLike, instanceAddress: AddressLike, user: AddressLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'proxy'): TypedContractMethod<
      [calls: ProxyWalletFactory.CallStruct[], ],
      [string[]],
      'payable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setImplementation'): TypedContractMethod<
      [_newImplementation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ImplementationUpdated'): TypedContractEvent<ImplementationUpdatedEvent.InputTuple, ImplementationUpdatedEvent.OutputTuple, ImplementationUpdatedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'ProxyCreation'): TypedContractEvent<ProxyCreationEvent.InputTuple, ProxyCreationEvent.OutputTuple, ProxyCreationEvent.OutputObject>;

    filters: {
      
      'ImplementationUpdated(address)': TypedContractEvent<ImplementationUpdatedEvent.InputTuple, ImplementationUpdatedEvent.OutputTuple, ImplementationUpdatedEvent.OutputObject>;
      ImplementationUpdated: TypedContractEvent<ImplementationUpdatedEvent.InputTuple, ImplementationUpdatedEvent.OutputTuple, ImplementationUpdatedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'ProxyCreation(address,address)': TypedContractEvent<ProxyCreationEvent.InputTuple, ProxyCreationEvent.OutputTuple, ProxyCreationEvent.OutputObject>;
      ProxyCreation: TypedContractEvent<ProxyCreationEvent.InputTuple, ProxyCreationEvent.OutputTuple, ProxyCreationEvent.OutputObject>;
    
    };
  }